### PR TITLE
Fix a typo, pdf toc, and eps orientation

### PR DESCRIPTION
**Pull request by tenomoto**
A typo in Illustratitions-j.pptx and toc are fixed.
In my environment (macOS psutils and ps2eps installed with MacPorts), I need further changes in the options for psselect and ps2eps.

### CODE REVIEW

**Comment by kenjihiranabe** [comment]
Thank you @tenomoto for your deep look into my work.
Where is the change your made to the Illustrations-j.pptx ? (I couldn't identify the spot !)

**Comment by tenomoto** [comment]
I replaced 直行化 with 直交化 in the annotation for A=QR on slide 12.

**Comment by kenjihiranabe** [comment]
merged all.

**Comment by kenjihiranabe** [comment]
After I merged your makefile, the graphics in the .pdf looks like UPSIDE DOWN.
Do you have any idea why this happens ?

image

I saw the "-R=-" option to the ps2eps you added.

Before adding this option, I turned this "vertical print mode" manually without "-R=-" and worked fine.

ppt-print

Hopefully, there's a good way to make this work in my repo as well as yours.

**Comment by kenjihiranabe** [comment]
OK, now I changed the ps2eps option to -R=+ and used normal landscape mode to print from pptx.
Hope this works for you too. @tenomoto

**Pull request merged**
